#服务器端口
server:
  port: 80
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/skytourism?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      #配置初始化大小、最大、最小（连接池）
      initial-size: 10
      max-idle: 30
      min-idle: 10
      #配置获取连接等待的超时时间
      max-wait-millis: 60000
      #间隔多久进行一次检测，检测需要关闭的连接
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    open-in-view: false

logging:
  level:
    root: info
  path: D://sky-tourism/

#audience
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: REST_API_USER
  expiresSecond: 120

